analyzer:
  plugins:
    - flutterando_metrics


flutterando_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting: 5
    number-of-parameters: 4
  metrics-exclude:
    - test/**
